### ISSUE TITLE
catkin_makeでエラー

### ISSUE THREAD

**Issue by tenpa1105** [vstoneofficial/scara_ros_samples#1]
マニュアルにしたがって、ROSの環境を構築し、ビルドを行いましたが、
catkin_make -DCATKIN_BLACKLIST_PACKAGES=""
でエラーが発生しました。

CMake Error at /opt/ros/melodic/share/catkin/cmake/catkin_package.cmake:224 (message):
  catkin_package() DEPENDS on the catkin package 'scara_robot_msgs' which
  must therefore be listed as a run dependency in the package.xml
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
  scara_ros_samples/scara_robot_samples/CMakeLists.txt:110 (catkin_package)

src/scara_robot_samples\package.xmlに
  <exec_depend>scara_robot_msgs</exec_depend>
を追加することで、ビルドに成功しました。

**Comment by vsfukatsu** [comment]
ご指摘いただきありがとうございます。ご提案いただいた方法を反映いたしました。
