### ISSUE TITLE
unable to find the required header file

### ISSUE THREAD

**Issue by bonedoz** [vstoneofficial/scara_ros_samples#2]
I downloaded the [`USBXpressHostSDK`](https://www.silabs.com/documents/public/software/USBXpressHostSDK-Linux.tar) following the instructions of the manual, but after decompression, there are no required header files(`Types.h` `silabs_defs.h` `silabs_sal.h`).
![DeepinScreenshot_select-area_20200925090342](https://user-images.githubusercontent.com/71833572/94215085-09f68f80-ff0e-11ea-9394-61af771ca46d.png)
![DeepinScreenshot_nautilus_20200925085927](https://user-images.githubusercontent.com/71833572/94214941-98b6dc80-ff0d-11ea-9cdf-3381bf5cd00e.png)

**Comment by vsfukatsu** [comment]
The files Types.h silabs_defs.h silabs_sal.h are not included in the USBXpressHostSDK and are located in 'scara_ros_samples/scara_robot_samples/includes/'.
Copy these files to 'CP2110_4/include/', which you can unzip the USBXpressHostSDK.

Types.h silabs_defs.h silabs_sal.hのファイルは、USBXpressHostSDKには含まれておらず、scara_ros_samples/scara_robot_samples/includes/ に存在します。
これらのファイルを、USBXpressHostSDKを解凍してできる CP2110_4/include にコピーしてください。

**Comment by jeanjean1** [comment]
The order of instructions is reversed in the documentation, but the problem should be solved if you follow the steps given by @toshimori . @bonedoz Could you close the issue if it is ?
